### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by plapcity** [spree-contrib/spree_affiliate#8]
WIll this be updated to work with the new versions of Spree?

**Comment by JDutil** [comment]
I'm going to go out on a limb and say no.  

This hasn't been touched in over 3 years so you would be better off starting from scratch...

I've got an affiliates extension I had worked on updating from another fork for a client, but they abandoned rolling their own solution in favor of using an affiliate SaaS solution.  You can look at it for something more up to date, but it isn't updated for the 2.2.x yet it should work for 2.0.x though if you want to just upgrade that one:
https://github.com/JDutil/spree_affiliates

Pull requests welcome.
